/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84786VLK
**     Component   : MC56F84786VLK
**     Version     : Component 01.006, Driver 01.01, CPU db: 3.50.001
**     Datasheet   : MC56F847XXRM Rev.1 06/2012
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-01-30, 18:37, # CodeGen: 149
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - asm void Cpu_Delay100US(word us100);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.01
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */
#include "LED1.h"
#include "LED2.h"
#include "SWITCH.h"
#include "Inhr1.h"
#include "Inhr2.h"
#include "Inhr3.h"
#include "Inhr4.h"
#include "KEY.h"
#include "Inhr5.h"
#include "Inhr6.h"
#include "Inhr7.h"
#include "Inhr8.h"
#include "SCI.h"
#include "HMI_OLED.h"
#include "TMR.h"
#include "LEFTPA.h"
#include "RIGHTPA.h"
#include "DRV_MEN.h"
#include "SERVO1.h"
#include "HS.h"
#include "VS.h"
#include "DMA_12.h"
#include "SERVO2.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile word SR_lock = 0U;            /* Lock */
volatile word SR_reg;                  /* Current value of the SR register */
/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MC56F84786VLK)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp
void Cpu_Interrupt(void)
{
  asm(DEBUGHLT);                       /* Halt the core and placing it in the debug processing state */
}

/*
** ===================================================================
**     Method      :  Cpu__ivINT_GPIOA (component MC56F84786VLK)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp saveall
void Cpu__ivINT_GPIOA(void)
{
  word regIntFlag_GPIOA_IPR = getReg(GPIOA_IPR);

  if (regIntFlag_GPIOA_IPR & GPIOA_IPR_IP1_MASK) { /* Is an interrupt flag set? */
  setReg16(GPIOA_IESR, GPIOA_IESR_IES1_MASK);
  }
  if (regIntFlag_GPIOA_IPR & GPIOA_IPR_IP2_MASK) { /* Is an interrupt flag set? */
  setReg16(GPIOA_IESR, GPIOA_IESR_IES2_MASK);
  }
  if (regIntFlag_GPIOA_IPR & GPIOA_IPR_IP1_MASK) { /* Is the interrupt flag set? */
    HS_OnInterrupt();                  /* Call the service routine */
  }
  if (regIntFlag_GPIOA_IPR & GPIOA_IPR_IP2_MASK) { /* Is the interrupt flag set? */
    VS_OnInterrupt();                  /* Call the service routine */
  }
}

/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC56F84786VLK)
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. Adding read
**         wait states for external program memory can cause delay
**         extension as well. The method is independent on selected
**         speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**     Returns     : Nothing
** ===================================================================
*/
/*lint -save  -e586 Disable MISRA rule (2.1) checking. Method is implemented using assembler. */
asm void Cpu_Delay100US(word us100)
{
  /* Total irremovable overhead: about 16 cycles */
  /* move.w: 2 cycles overhead (load parameter into register) */
  /* jsr:    5 cycles overhead (jump to subroutine) */
  /* rts:    8 cycles overhead (return from subroutine) */
  /* nop:    1 cycles overhead (aditional nops) */

  loop:
  /* 100 us delay block begin */
  /*
   * Delay
   *   - requested                  : 100 us @ 200MHz,
   *   - possible                   : 20000 c, 100000 ns
   *   - without removable overhead : 19994 c, 99970 ns
   */
  adda #2, SP                          /* (1 c: 5 ns) move SP forward */
  move.l A10, X:(SP)                   /* (2 c: 10 ns) push A */
  move.w #0x2705, A                    /* (2 c: 10 ns) number of iterations */
  do A, label0                         /* (8 c: 40 ns) repeat 9989x nop */
    nop                                /* (1 c: 5 ns) wait for 1 c */
  label0:
  move.l X:(SP), A                     /* (2 c: 10 ns) pop A */
  suba #2, SP                          /* (1 c: 5 ns) move SP back */
  /* 100 us delay block end */
  dec.w Y0                             /* us100 parameter is passed via Y0 register */
  jne loop                             /* next loop */
  nop                                  /* avoid pipeline conflicts */
  rts                                  /* return from subroutine */
}
/*lint -restore Enable MISRA rule (2.1) checking. */

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC56F84786VLK)
**     Description :
**         Disables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC56F84786VLK)
**     Description :
**         Enables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC56F84786VLK)
**     Description :
**         Sets low power mode - Stop mode.
**         For more information about the stop mode see this CPU
**         documentation.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC56F84786VLK)
**     Description :
**         Sets low power mode - Wait mode.
**         For more information about the wait mode see this CPU
**         documentation.
**         Release from wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC56F84786VLK)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void init_56800_(void);         /* Forward declaration of external startup function declared in startup file */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

void _EntryPoint(void)
{
  #pragma constarray off

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MC56F84786VLK "Cpu" init code ... ***/

  /*** PE initialization code after reset ***/

  /* Disable watchdog after reset based on the setting of the "Watchdog" property in CPU component */
  /* COP_CTRL: ??=0,??=0,??=0,??=0,??=0,??=0,PSS=3,INTEN=0,CLKSEL=0,CLOREN=0,CSEN=0,CWEN=0,CEN=0,CWP=0 */
  setReg16(COP_CTRL, 0x0300U);          

  /* System clock initialization */
  setRegBitGroup(OCCS_OSCTL1, FREQ_TRIM8M, ((*(word *)0xE42C) & 0x03FFU)); /* Trim the 8MHz internal relaxation oscillator, frequency trim value */
  clrSetReg16Bits(OCCS_OSCTL1, OCCS_OSCTL1_ROPD_MASK, OCCS_OSCTL1_CLK_MODE_MASK); /* Enable internal 8MHz oscillator and select an external clock bypass mode */
  setRegBitGroup(OCCS_CTRL, PRECS, 0U); /* Select an internal 8MHz clock source for the CPU core */
  clrSetReg16Bits(OCCS_CTRL, OCCS_CTRL_PLLPD_MASK, OCCS_CTRL_LCKON_MASK); /* Enable PLL, LCKON and select clock source from prescaler */
  /* OCCS_DIVBY: LORTP=2,COD=0,??=0,??=0,PLLDB=0x31 */
  setReg16(OCCS_DIVBY, 0x2031U);       /* Set the clock prescalers */ 
  while(!getRegBit(OCCS_STAT, LCK0)){} /* Wait for PLL lock */
  setReg16Bits(OCCS_CTRL, OCCS_CTRL_ZSRC_MASK); /* Enable PLL, LCKON and select clock source from prescaler */
  /* OCCS_PROT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRQEP=0,OSCEP=0,PLLEP=0 */
  setReg16(OCCS_PROT, 0x00U);          /* Set the OCCS protection register */ 
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

  asm(JMP init_56800_);                /* Jump to C startup code */
}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC56F84786VLK)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
      /* Initialization of the SIM module */
  /* SIM_MISC0: PIT_MSTR=0 */
  clrReg16Bits(SIM_MISC0, 0x01U);       
  /* SIM_CTRL: RST_FILT=0,DMAEbl=3,OnceEbl=0,STOP_disable=0,WAIT_disable=0 */
  clrSetReg16Bits(SIM_CTRL, 0x052FU, 0xC0U); 
  /* SIM_PWR: SR12STDBY=0,SR27PDN=0,SR27STDBY=0,LRSTDBY=0 */
  clrReg16Bits(SIM_PWR, 0xFFU);         
  /* SIM_CLKOUT: CLKODIV=0,CLKDIS1=1,CLKOSEL1=0,CLKDIS0=1,CLKOSEL0=0 */
  clrSetReg16Bits(SIM_CLKOUT, 0xE387U, 0x1020U); 
  /* SIM_PCE0: TA0=1,TA1=1,TA2=1,TA3=0,TB0=1,TB1=0,TB2=0,TB3=0,GPIOA=1,GPIOB=0,GPIOC=1,GPIOD=1,GPIOE=1,GPIOF=1,GPIOG=1 */
  clrSetReg16Bits(SIM_PCE0, 0x1720U, 0xE85FU); 
  /* SIM_PCE1: DAC=0,SCI0=0,SCI1=0,SCI2=1,QSPI0=0,QSPI1=0,IIC0=0,IIC1=0,FLEXCAN=0 */
  clrSetReg16Bits(SIM_PCE1, 0x3B61U, 0x0400U); 
  /* SIM_PCE2: CMPA=0,CMPB=0,CMPC=0,CMPD=0,SARADC=0,CYCADC=1,CRC=0,QDC=0,PIT0=0,PIT1=0,PDB0=0,PDB1=0 */
  clrSetReg16Bits(SIM_PCE2, 0x1F3FU, 0x80U); 
  /* SIM_PCE3: PWMACH0=1,PWMACH1=1,PWMACH2=1,PWMACH3=1,PWMBCH0=0,PWMBCH1=1,PWMBCH2=0,PWMBCH3=0 */
  clrSetReg16Bits(SIM_PCE3, 0x0BU, 0xF4U); 
  /* SIM_SD0: TA0=0,TA1=0,TA2=0,TA3=0,TB0=0,TB1=0,TB2=0,TB3=0,GPIOA=0,GPIOB=0,GPIOC=0,GPIOD=0,GPIOE=0,GPIOF=0,GPIOG=0 */
  clrReg16Bits(SIM_SD0, 0xFF7FU);       
  /* SIM_SD1: DAC=0,SCI0=0,SCI1=0,SCI2=0,QSPI0=0,QSPI1=0,IIC0=0,IIC1=0,FLEXCAN=0 */
  clrReg16Bits(SIM_SD1, 0x3F61U);       
  /* SIM_SD2: CMPA=0,CMPB=0,CMPC=0,CMPD=0,SARADC=0,CYCADC=0,CRC=0,QDC=0,PIT0=0,PIT1=0,PDB0=0,PDB1=0 */
  clrReg16Bits(SIM_SD2, 0x1FBFU);       
  /* SIM_SD3: PWMACH0=0,PWMACH1=0,PWMACH2=0,PWMACH3=0,PWMBCH0=0,PWMBCH1=0,PWMBCH2=0,PWMBCH3=0 */
  clrReg16Bits(SIM_SD3, 0xFFU);         
  /* SIM_PROT: PMODE=0,GDP=0,PCEP=0,GIPSP=0 */
  clrReg16Bits(SIM_PROT, 0xFFU);        
  /* SIM_PCR: ??=0,??=0,SCI0_CR=1,SCI1_CR=1,SCI2_CR=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(SIM_PCR, 0x3800U);          /* Set the QSCI0; QSCI1; QSCI2 module clock rates */ 
      /* Initialization of the MCM module */
  /* MCM_UPRAMBAR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,RBA=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_UPRAMBAR, 0x00UL);       
  /* MCM_UFLASHBAR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FBA=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_UFLASHBAR, 0x00UL);      
  /* MCM_CPCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,IBDIS=0,SRDIS=0,RCDIS=0,INSDIS=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_CPCR, 0x00UL);           
  /* MCM_RPCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,RL=0,RPE=0 */
  setReg32(MCM_RPCR, 0x00UL);           
      /* Initialization of the GPIOA module */
  /* GPIOA_DRIVE: DRIVE11=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOA_DRIVE, 0x08FFU);   
  /* GPIOA_SRE: SRE11=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOA_SRE, 0x08FFU);     
      /* Initialization of the GPIOB module */
  /* GPIOB_DRIVE: DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOB_DRIVE, 0x01FFU);   
  /* GPIOB_SRE: SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOB_SRE, 0x01FFU);     
      /* Initialization of the GPIOC module */
  /* GPIOC_DRIVE: DRIVE15=0,DRIVE14=0,DRIVE13=0,DRIVE12=0,DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIOC_DRIVE, 0x00U);         
  /* GPIOC_SRE: SRE15=1,SRE14=1,SRE13=1,SRE12=1,SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16(GPIOC_SRE, 0xFFFFU);         
      /* Initialization of the GPIOD module */
  /* GPIOD_DRIVE: DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOD_DRIVE, 0xFFU);     
  /* GPIOD_SRE: SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=0,SRE2=1,SRE1=0,SRE0=1 */
  clrSetReg16Bits(GPIOD_SRE, 0x0AU, 0xF5U); 
      /* Initialization of the GPIOE module */
  /* GPIOE_DRIVE: DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOE_DRIVE, 0xFFU);     
  /* GPIOE_SRE: SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOE_SRE, 0xFFU);       
      /* Initialization of the GPIOF module */
  /* GPIOF_DRIVE: DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOF_DRIVE, 0x07FFU);   
  /* GPIOF_SRE: SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOF_SRE, 0x07FFU);     
      /* Initialization of the GPIOG module */
  /* GPIOG_DRIVE: DRIVE11=0,DRIVE7=0,DRIVE6=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOG_DRIVE, 0x08CFU);   
  /* GPIOG_SRE: SRE11=1,SRE7=1,SRE6=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOG_SRE, 0x08CFU);     
/*lint -save  -e586 Disable MISRA rule (2.1) checking. Functionality is implemented using assembler. */
  /* Shadow registers initialization */
  asm {
    swap shadows
    nop
    nop
    move.l #0, R0
    move.l #0, R1
    move.l #0, R2
    move.l #0, R3
    move.l #0, R4
    move.l #0, R5
    move.l #0, N
    moveu.w #65535, N3
    moveu.w #65535, M01
    nop
    nop
    swap shadows
  }
/*lint -restore Enable MISRA rule (2.1) checking. */
  /* Common initialization of the CPU registers */
  /* GPIOF_IENR: IEN8=0,IEN7=0,IEN6=0,IEN5=0 */
  clrReg16Bits(GPIOF_IENR, 0x01E0U);    
  /* GPIOF_IAR: IA8=0,IA7=0,IA6=0,IA5=0 */
  clrReg16Bits(GPIOF_IAR, 0x01E0U);     
  /* GPIOF_IESR: IES8=1,IES7=1,IES6=1,IES5=1 */
  setReg16Bits(GPIOF_IESR, 0x01E0U);    
  /* GPIOF_PPMODE: PPMODE8=0,PPMODE5=0 */
  clrReg16Bits(GPIOF_PPMODE, 0x0120U);  
  /* GPIOF_DR: D8=1,D5=1 */
  setReg16Bits(GPIOF_DR, 0x0120U);      
  /* GPIOF_DDR: DD8=1,DD7=0,DD6=0,DD5=1 */
  clrSetReg16Bits(GPIOF_DDR, 0xC0U, 0x0120U); 
  /* GPIOF_PER: PE8=0,PE7=0,PE6=0,PE5=0 */
  clrReg16Bits(GPIOF_PER, 0x01E0U);     
  /* GPIOF_PUR: PU7=0,PU6=0 */
  clrReg16Bits(GPIOF_PUR, 0xC0U);       
  /* GPIOG_IENR: IEN7=0,IEN2=0 */
  clrReg16Bits(GPIOG_IENR, 0x84U);      
  /* GPIOG_IAR: IA7=0,IA2=0 */
  clrReg16Bits(GPIOG_IAR, 0x84U);       
  /* GPIOG_IESR: IES7=1,IES2=1 */
  setReg16Bits(GPIOG_IESR, 0x84U);      
  /* GPIOG_PUR: PU7=0 */
  clrReg16Bits(GPIOG_PUR, 0x80U);       
  /* GPIOG_DR: D2=0 */
  clrReg16Bits(GPIOG_DR, 0x04U);        
  /* GPIOG_DDR: DD7=0,DD2=1 */
  clrSetReg16Bits(GPIOG_DDR, 0x80U, 0x04U); 
  /* GPIOG_PER: PE7=0,PE2=0,PE1=1,PE0=1 */
  clrSetReg16Bits(GPIOG_PER, 0x84U, 0x03U); 
  /* GPIOC_IENR: IEN15=0,IEN14=0,IEN12=0,IEN11=0,IEN10=0,IEN9=0,IEN8=0 */
  clrReg16Bits(GPIOC_IENR, 0xDF00U);    
  /* GPIOC_IAR: IA15=0,IA14=0,IA12=0,IA11=0,IA10=0,IA9=0,IA8=0 */
  clrReg16Bits(GPIOC_IAR, 0xDF00U);     
  /* GPIOC_IESR: IES15=1,IES14=1,IES12=1,IES11=1,IES10=1,IES9=1,IES8=1 */
  setReg16Bits(GPIOC_IESR, 0xDF00U);    
  /* GPIOC_PUR: PU15=0,PU14=0,PU13=0,PU6=0,PU4=0,PU3=0 */
  clrReg16Bits(GPIOC_PUR, 0xE058U);     
  /* GPIOC_DR: D12=0,D11=1,D10=1,D9=1,D8=1 */
  clrSetReg16Bits(GPIOC_DR, 0x1000U, 0x0F00U); 
  /* GPIOC_DDR: DD15=0,DD14=0,DD12=1,DD11=1,DD10=1,DD9=1,DD8=1 */
  clrSetReg16Bits(GPIOC_DDR, 0xC000U, 0x1F00U); 
  /* GPIOC_PER: PE15=0,PE14=0,PE13=1,PE12=0,PE11=0,PE10=0,PE9=0,PE8=0,PE6=1,PE4=1,PE3=1 */
  clrSetReg16Bits(GPIOC_PER, 0xDF00U, 0x2058U); 
  /* GPIOE_IENR: IEN7=0,IEN5=0,IEN4=0 */
  clrReg16Bits(GPIOE_IENR, 0xB0U);      
  /* GPIOE_IAR: IA7=0,IA5=0,IA4=0 */
  clrReg16Bits(GPIOE_IAR, 0xB0U);       
  /* GPIOE_IESR: IES7=1,IES5=1,IES4=1 */
  setReg16Bits(GPIOE_IESR, 0xB0U);      
  /* GPIOE_PUR: PU7=0,PU5=0,PU4=0 */
  clrReg16Bits(GPIOE_PUR, 0xB0U);       
  /* GPIOE_DDR: DD7=0,DD5=0,DD4=0 */
  clrReg16Bits(GPIOE_DDR, 0xB0U);       
  /* GPIOE_PER: PE7=0,PE5=0,PE4=0 */
  clrReg16Bits(GPIOE_PER, 0xB0U);       
  /* GPIOD_PER: PE6=1,PE5=1,PE4=1 */
  setReg16Bits(GPIOD_PER, 0x70U);       
  /* SIM_GPSDL: D6=0,D5=0 */
  clrReg16Bits(SIM_GPSDL, 0x3C00U);     
  /* GPIOC_PPMODE: PPMODE12=1,PPMODE11=1,PPMODE10=1,PPMODE9=1,PPMODE8=1 */
  setReg16Bits(GPIOC_PPMODE, 0x1F00U);  
  /* INTC_IPR2: TMRA_0=2 */
  clrSetReg16Bits(INTC_IPR2, 0x40U, 0x80U); 
  /* TMRA_0_ENBL: ENBL&=~7 */
  clrReg16Bits(TMRA_0_ENBL, 0x07U);     
  /* SIM_GPSCL: C6=0,C4=0,C3=0 */
  clrReg16Bits(SIM_GPSCL, 0x33C0U);     
  /* SIM_IPS0: TA3=0,TA2=0,TA1=0,TA0=0 */
  clrReg16Bits(SIM_IPS0, 0x0F00U);      
  /* SIM_GPSCH: C13=0 */
  clrReg16Bits(SIM_GPSCH, 0x0C00U);     
  /* GPIOG_PPMODE: PPMODE2=1 */
  setReg16Bits(GPIOG_PPMODE, 0x04U);    
  /* SIM_GPSGL: G1=0,G0=1 */
  clrSetReg16Bits(SIM_GPSGL, 0x04U, 0x01U); 
  /* INTC_IPR12: GPIOA=3 */
  setReg16Bits(INTC_IPR12, 0x30U);      
  /* GPIOA_IAR: IA2=0,IA1=0 */
  clrReg16Bits(GPIOA_IAR, 0x06U);       
  /* GPIOA_IPR: IP2=0,IP1=0 */
  clrReg16Bits(GPIOA_IPR, 0x06U);       
  /* GPIOA_IPOLR: IPOL2=1,IPOL1=0 */
  clrSetReg16Bits(GPIOA_IPOLR, 0x02U, 0x04U); 
  /* GPIOA_PUR: PU2=0,PU1=0 */
  clrReg16Bits(GPIOA_PUR, 0x06U);       
  /* GPIOA_DDR: DD2=0,DD1=0 */
  clrReg16Bits(GPIOA_DDR, 0x06U);       
  /* GPIOA_PER: PE2=0,PE1=0 */
  clrReg16Bits(GPIOA_PER, 0x06U);       
  /* INTC_IPR3: DMACH0=3 */
  setReg16Bits(INTC_IPR3, 0xC0U);       
  /* XBARA_SEL3: SEL6=0x10 */
  clrSetReg16Bits(XBARA_SEL3, 0x2FU, 0x10U); 
  /* TMRB_0_ENBL: ENBL&=~1 */
  clrReg16Bits(TMRB_0_ENBL, 0x01U);     
  /* Initialization of the SIM module */
  /* ### MultiBitIO "SWITCH" init code ... */
  /* ### MultiBitIO "KEY" init code ... */
  /* ### Asynchro serial "SCI" init code ... */
  SCI_Init();
  /* ### TimerInt "TMR" init code ... */
  TMR_Init();
  /* ### PulseAccumulator "LEFTPA" init code ... */
  LEFTPA_Init();
  /* ### PulseAccumulator "RIGHTPA" init code ... */
  RIGHTPA_Init();
  /* ### Programable pulse generation "SERVO1" init code ... */
  SERVO1_Init();
  /* ### DMAChannel "DMA_12" init code ... */
  DMA_12_Init();
  /* ### Pulse width modulation "SERVO2" init code ... */
  SERVO2_Init();
  /* Common peripheral initialization - ENABLE */
  /* TMRA_0_ENBL: ENBL|=7 */
  setReg16Bits(TMRA_0_ENBL, 0x07U);     
  /* PWMB_MASK: MASKA&=~2 */
  clrReg16Bits(PWMB_MASK, 0x0200U);     
  /* PWMB_OUTEN: PWMA_EN|=2 */
  setReg16Bits(PWMB_OUTEN, 0x0200U);    
  /* PWMB_DTSRCSEL: SM1SEL23=0 */
  clrReg16Bits(PWMB_DTSRCSEL, 0xC0U);   
  /* PWMB_SM1CTRL2: FORCE=1 */
  setReg16Bits(PWMB_SM1CTRL2, 0x40U);   
  /* PWMB_MCTRL: RUN|=2 */
  setReg16Bits(PWMB_MCTRL, 0x0200U);    
  /* PWMB_SM1STS: RF=1 */
  setReg16Bits(PWMB_SM1STS, 0x1000U);   
  /* GPIOA_IESR: IES2=1,IES1=1 */
  setReg16Bits(GPIOA_IESR, 0x06U);      
  /* GPIOA_IENR: IEN2=1,IEN1=1 */
  setReg16Bits(GPIOA_IENR, 0x06U);      
  /* TMRB_0_ENBL: ENBL|=1 */
  setReg16Bits(TMRB_0_ENBL, 0x01U);     
  __EI(0);                             /* Enable interrupts of the selected priority level */
}

/* END Cpu. */

