/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : DMA_12.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84786VLK
**     Component   : DMAChannel
**     Version     : Component 01.069, Driver 01.10, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-01-30, 18:37, # CodeGen: 149
**     Abstract    :
**         This bean "DMAChannel" implements DMA channel.

**     Settings    :
**         DMA channel                 : DMA_Channel0
**
**         DMA interrupt
**             Vector name             : INT_DMA0
**             Interrupt priority      : 2
**
**         Source address              : (unsigned long)((unsigned char*)&ADC12_RSLT0+1)
**         Destination address         : (unsigned long)g_nCamFrameBuffer
**
**         Block length                : IMG_COLS
**
**     Contents    :
**         SetDestinationAddress - void DMA_12_SetDestinationAddress(void* addr);
**         SetDataSize           - byte DMA_12_SetDataSize(word size);
**         Start                 - void DMA_12_Start(void);
**         Stop                  - void DMA_12_Stop(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file DMA_12.c
** @version 01.10
** @brief
**         This bean "DMAChannel" implements DMA channel.

*/         
/*!
**  @addtogroup DMA_12_module DMA_12 module documentation
**  @{
*/         

/* MODULE DMA_12. */

#include "Events.h"
#include "DMA_12.h"

#define DONE_FLAG                      0x01U
#define ERROR_FLAGS                    0x70U

/* User external destination object declaration */
#include "Cam.h"


/*
** ===================================================================
**     Method      :  DMA_12_SetDestinationAddress (component DMAChannel)
**     Description :
**         Specifies address of the destination buffer for DMA transfer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * addr            - Pointer to the destination buffer for
**                           DMA transfer.
**     Returns     : Nothing
** ===================================================================
*/
/*
void DMA_12_SetDestinationAddress(void* addr)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  DMA_12_SetDataSize (component DMAChannel)
**     Description :
**         Specifies the DMA data size - number of data to be
**         transferred.
**     Parameters  :
**         NAME            - DESCRIPTION
**         size            - Number of bytes to be transferred.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
/*
byte DMA_12_SetDataSize(word size)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  DMA_12_Start (component DMAChannel)
**     Description :
**         Starts DMA transfer. If Peripheral mapping is used this
**         method enables peripheral requests and transfer starts after
**         peripheral request is asserted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DMA_12_Start(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  DMA_12_Stop (component DMAChannel)
**     Description :
**         Aborts DMA transfer. If Peripheral mapping is used this
**         method also disables peripheral requests.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DMA_12_Stop(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  DMA_12_Interrupt (component DMAChannel)
**
**     Description :
**         The method services the transfer complete interrupt of the 
**         selected peripheral(s) and eventually invokes the components 
**         event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp saveall
void DMA_12_Interrupt(void)
{
  setReg32Bit(DMA_DSR_BCR0, DONE);     /* Clear status bits */
  DMA_12_OnComplete();                 /* If yes then invoke user event */
}

/*
** ===================================================================
**     Method      :  DMA_12_Init (component DMAChannel)
**
**     Description :
**         Initializes the associated peripheral(s) and the components 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void DMA_12_Init(void)
{
  /* Disable DMA channel 0 */
  /* DMA_DCR0: EINT=0,ERQ=0,CS=0,AA=0,??=0,??=0,??=0,??=0,??=0,SINC=0,SSIZE=0,DINC=0,DSIZE=0,START=0,SMOD=0,DMOD=0,D_REQ=0,??=0,LINKCC=0,LCH1=0,LCH2=0 */
  setReg32(DMA_DCR0, 0x00);
  /* Clear flags */
  /* DMA_DSR_BCR0: ??=0,CE=0,BES=0,BED=0,??=0,REQ=0,BSY=0,DONE=1,BCR=0 */
  setReg32Bit(DMA_DSR_BCR0, DONE);
  /* DMA_REQC: CFSM0=1,??=0,??=0,??=0,DMAC0=0,CFSM1=0,??=0,??=0,??=0,DMAC1=0,CFSM2=0,??=0,??=0,??=0,DMAC2=0,CFSM3=0,??=0,??=0,??=0,DMAC3=0 */
  setReg32Bit(DMA_REQC, CFSM0);
  /* DMA_REQC: CFSM0=0,??=0,??=0,??=0,DMAC0=0x0C,CFSM1=0,??=0,??=0,??=0,DMAC1=0,CFSM2=0,??=0,??=0,??=0,DMAC2=0,CFSM3=0,??=0,??=0,??=0,DMAC3=0 */
  setReg32BitGroupVal(DMA_REQC, DMAC0, 0x0C);
  /* DMA_SAR0: SAR = (unsigned long)((unsigned char*)&ADC12_RSLT0+1) */
  DMA_SAR0 = (unsigned long)((unsigned char*)&ADC12_RSLT0+1);
  /* DMA_DAR0: DAR = (unsigned long)g_nCamFrameBuffer */
  DMA_DAR0 = (unsigned long)g_nCamFrameBuffer;
  /* DMA_DCR0: EINT=1,ERQ=0,CS=1,AA=0,??=0,??=0,??=0,??=0,??=0,SINC=0,SSIZE=1,DINC=1,DSIZE=1,START=0,SMOD=0,DMOD=0,D_REQ=1,??=0,LINKCC=0,LCH1=0,LCH2=0 */
  setReg32(DMA_DCR0, 0xA01A0080);
  /* DMA_DSR_BCR0: BCR = IMG_COLS */
  DMA_DSR_BCR0 = (IMG_COLS) & DMA_DSR_BCR0_BCR_MASK;
  /* Enable peripheral requests */
  /* DMA_DCR0: EINT=0,ERQ=1,CS=0,AA=0,??=0,??=0,??=0,??=0,??=0,SINC=0,SSIZE=0,DINC=0,DSIZE=0,START=0,SMOD=0,DMOD=0,D_REQ=0,??=0,LINKCC=0,LCH1=0,LCH2=0 */
  setReg32Bit(DMA_DCR0, ERQ);
}

/* END DMA_12. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
