/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : HMI_OLED.h
**     Project     : ProcessorExpert
**     Processor   : MC56F84786VLK
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.22, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-01-30, 18:37, # CodeGen: 149
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : GPIOC_High
**
**         Bit mask of the port        : 1F00
**         Number of bits/pins         : 5
**         Single bit numbers          : 0 to 4
**         Values range                : 0 to 31
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 15 = 00FH
**         Initial pull option         : off
**
**         Port data register          : GPIOC_DR  [E221]
**         Port control register       : GPIOC_DDR [E222]
**         Port function register      : GPIOC_PER [E223]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    41   |   GPIOC8/MISO0/RXD0/XB_IN9
**                    1      |    42   |   GPIOC9/SCK0/XB_IN4
**                    2      |    43   |   GPIOC10/MOSI0/XB_IN5/MISO0
**                    3      |    47   |   GPIOC11/CANTX/SCL1/TXD1
**                    4      |    48   |   GPIOC12/CANRX/SDA1/RXD1
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         PutBit - void HMI_OLED_PutBit(byte Bit, bool Val);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file HMI_OLED.h
** @version 01.22
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup HMI_OLED_module HMI_OLED module documentation
**  @{
*/         

#ifndef __HMI_OLED_H
#define __HMI_OLED_H

/* MODULE HMI_OLED. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"

#define HMI_OLED_PIN_MASK       ((word)0x1F00) /* Pin mask */
#define HMI_OLED_PIN_MASK_SHIFTED ((byte)0x1F) /* Shifted pin mask by 8, if pin mask is greater than 128 */
#define HMI_OLED_PIN_MASK_JUSTIFIED ((byte)0x1F) /* Justified pin mask to the right, if Pin0 index within the port is nonzero */


/*
** ===================================================================
**     Method      :  HMI_OLED_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 4)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void HMI_OLED_PutBit(byte Bit, bool Val);


/* END HMI_OLED. */

#endif /* __HMI_OLED_H*/
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
