/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SERVO1.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84786VLK
**     Component   : PWM
**     Version     : Component 02.240, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-01-30, 18:37, # CodeGen: 149
**     Abstract    :
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       64            |  GPIOG1/PWMB_1A/XB_OUT7
**             ----------------------------------------------------
**
**         Timer name                  : PWMB_SM1_Timer [16-bit]
**         Counter                     : PWMB_SM1CNT [E730]
**         Mode register               : PWMB_SM1CTRL [E733]
**         Run register                : PWMB_SM1CTRL [E733]
**         Prescaler                   : PWMB_SM1CTRL [E733]
**         Compare register            : PWMB_SM1VAL2 [E739]
**         Flip-flop register          : PWMB_SM1VAL3 [E73B]
**
**         User handling procedure     : not specified
**
**         Port name                   : GPIOG_Low
**         Bit number (in port)        : 1
**         Bit mask of the port        : 0002
**         Port data register          : GPIOG_DR  [E261]
**         Port control register       : GPIOG_DDR [E262]
**         Port function register      : GPIOG_PER [E263]
**
**         Initialization:
**              Output level           : high
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-32
**             Clock                   : 3125000 Hz
**           Initial value of            period     pulse width
**             Xtal ticks              : 167772     12001
**             microseconds            : 20972      1500
**             milliseconds            : 21         2
**             seconds (real)          : 0.02097152 0.00150016
**
**     Contents    :
**         SetDutyUS - byte SERVO1_SetDutyUS(word Time);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SERVO1.c
** @version 01.00
** @brief
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
*/         
/*!
**  @addtogroup SERVO1_module SERVO1 module documentation
**  @{
*/         


/* MODULE SERVO1. */

#include "SERVO1.h"

static word RatioStore;                /* Ratio of L-level to H-level */

/* Internal method prototypes */
static void SetRatio(void);

#define SetPV(Val) setRegBitGroup(PWMB_SM1CTRL,PRSC,(Val))

/*
** ===================================================================
**     Method      :  SetRatio (component PWM)
**
**     Description :
**         Calculates and sets new duty ratio. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(void)
{
  setReg(PWMB_SM1VAL3,(word)((((dword)(getReg(PWMB_SM1VAL1))+1U) * (dword)RatioStore) >> 0x10U)); /* Calculate new value according to the given ratio */
  setRegBit(PWMB_MCTRL,LDOK1);         /* Load counter and modulo registers into buffers */
}
/*
** ===================================================================
**     Method      :  SERVO1_SetDutyUS (component PWM)
**     Description :
**         This method sets the new duty value of the output signal.
**         The duty is expressed in microseconds as a 16-bit
**         unsigned integer number.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Time            - Duty to set [in microseconds]
**                      (0 to 20972 us in high speed mode)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte SERVO1_SetDutyUS(word Time)
{
  dlong rtval;                         /* Result of two 32-bit numbers multiplication */

  if (Time >= (word)0x51ECU) {         /* Is the given value out of range? */
    return ERR_RANGE;                  /* If yes then error */
  }
  PE_Timer_LngMul((dword)Time,0x03200000UL,&rtval); /* Multiply given value and high speed CPU mode coefficient */
  if (PE_Timer_LngHi3(rtval[0],rtval[1],&RatioStore)) { /* Is the result greater or equal than 65536 ? */
    RatioStore = (word)0xFFFFU;        /* If yes then use maximal possible value */
  }
  SetRatio();                          /* Calculate and set up new appropriate duty value */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SERVO1_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SERVO1_Init(void)
{
  /* PWMB_SWCOUT: SM1OUT23=1 */
  setReg16Bits(PWMB_SWCOUT, 0x08U);     
  /* PWMB_DTSRCSEL: SM1SEL23=2 */
  clrSetReg16Bits(PWMB_DTSRCSEL, 0x40U, 0x80U); 
  /* PWMB_SM1CTRL2: DBGEN=1,WAITEN=1,INDEP=1,PWM23_INIT=1,PWM45_INIT=1,PWMX_INIT=0,INIT_SEL=0,FRCEN=0,FORCE=1,FORCE_SEL=0,RELOAD_SEL=0,CLK_SEL=0 */
  setReg16(PWMB_SM1CTRL2, 0xF840U);     
  /* PWMB_SM1DISMAP0: ??=0,??=0,??=0,??=0,DIS0X=0,DIS0B=0,DIS0A=0 */
  setReg16(PWMB_SM1DISMAP0, 0x00U);     
  /* PWMB_SM1OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=0,POLB=0,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWMB_SM1OCTRL, 0x00U);       
  /* PWMB_SM1FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC_PU=0,??=0,??=0,??=0,FRAC45_EN=0,??=0,FRAC23_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWMB_SM1FRCTRL, 0x00U);      
  /* PWMB_SM1DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0 */
  setReg16(PWMB_SM1DTCNT0, 0x00U);      
  /* PWMB_SM1DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0 */
  setReg16(PWMB_SM1DTCNT1, 0x00U);      
  /* PWMB_SM1INIT: INIT=0 */
  setReg16(PWMB_SM1INIT, 0x00U);        
  RatioStore = (word)0x1250U;          /* Store initial value of the ratio */
  /* PWMB_SM1VAL2: VAL2=0 */
  setReg16(PWMB_SM1VAL2, 0x00U);        
  /* PWMB_SM1VAL3: VAL3=0x1250 */
  setReg16(PWMB_SM1VAL3, 0x1250U);      
  /* PWMB_SM1VAL1: VAL1=0xFFFF */
  setReg16(PWMB_SM1VAL1, 0xFFFFU);      
  SetPV((byte)0x05);                   /* Set prescaler register according to the selected high speed CPU mode */
  /* PWMB_MCTRL: LDOK|=2 */
  setReg16Bits(PWMB_MCTRL, 0x02U);      
}

/* END SERVO1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
