/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SERVO2.c
**     Project     : ProcessorExpert
**     Processor   : MC56F84786VLK
**     Component   : PWM
**     Version     : Component 02.240, Driver 02.06, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-01-30, 18:37, # CodeGen: 149
**     Abstract    :
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       63            |  GPIOG0/PWMB_1B/XB_OUT6
**             ----------------------------------------------------
**
**         Timer name                  : TMRB0 [16-bit]
**         Counter                     : TMRB_0_CNTR [E185]
**         Mode register               : TMRB_0_CTRL [E186]
**         Run register                : TMRB_0_CTRL [E186]
**         Prescaler                   : TMRB_0_CTRL [E186]
**         Compare register            : TMRB_0_COMP1 [E180]
**         Flip-flop register          : TMRB_0_SCTRL [E187]
**
**         User handling procedure     : not specified
**
**         Port name                   : GPIOG_Low
**         Bit number (in port)        : 0
**         Bit mask of the port        : 0001
**         Port data register          : GPIOG_DR  [E261]
**         Port control register       : GPIOG_DDR [E262]
**         Port function register      : GPIOG_PER [E263]
**
**         Initialization:
**              Output level           : high
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-32
**             Clock                   : 3125000 Hz
**           Initial value of            period     pulse width
**             Xtal ticks              : 167772     12001
**             microseconds            : 20972      1500
**             milliseconds            : 21         2
**             seconds (real)          : 0.02097152 0.00150016
**
**     Contents    :
**         SetDutyUS - byte SERVO2_SetDutyUS(word Time);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SERVO2.c
** @version 02.06
** @brief
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
*/         
/*!
**  @addtogroup SERVO2_module SERVO2 module documentation
**  @{
*/         


/* MODULE SERVO2. */

#include "SERVO2.h"

static word RatioStore;                /* Ratio of L-level to H-level */

/* Internal method prototypes */
static void SetRatio(void);

#define SetPV(Val) setRegBitGroup(TMRB_0_CTRL,PCS,(Val))

/*
** ===================================================================
**     Method      :  SetRatio (component PWM)
**
**     Description :
**         Calculates and sets new duty ratio. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(void)
{
  setReg(TMRB_0_COMP1,RatioStore?(RatioStore-1U):0U); /* Store ratio to compare register */
}
/*
** ===================================================================
**     Method      :  SERVO2_SetDutyUS (component PWM)
**     Description :
**         This method sets the new duty value of the output signal.
**         The duty is expressed in microseconds as a 16-bit
**         unsigned integer number.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Time            - Duty to set [in microseconds]
**                      (0 to 20972 us in high speed mode)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte SERVO2_SetDutyUS(word Time)
{
  dlong rtval;                         /* Result of two 32-bit numbers multiplication */

  if (Time >= 0x51ECU) {               /* Is the given value out of range? */
    return ERR_RANGE;                  /* If yes then error */
  }
  PE_Timer_LngMul((dword)Time,0x03200000UL,&rtval); /* Multiply given value and high speed CPU mode coefficient */
  if (PE_Timer_LngHi3(rtval[0],rtval[1],&RatioStore)) { /* Is the result greater or equal than 65536 ? */
    RatioStore = 0xFFFFU;              /* If yes then use maximal possible value */
  }
  SetRatio();                          /* Calculate and set up new appropriate duty value */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SERVO2_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SERVO2_Init(void)
{
  RatioStore = (word)0x1250U;          /* Store initial value of the ratio */
  setReg(TMRB_0_CNTR,0);               /* Reset counter */
  /* TMRB_0_SCTRL: TCF=0,TCFIE=0,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,CAPTURE_MODE=0,MSTR=0,EEOF=0,VAL=0,FORCE=1,OPS=1,OEN=1 */
  setReg(TMRB_0_SCTRL,0x07);           /* Enable output */
  setReg(TMRB_0_COMP1,0x124F);         /* Store initial value to the duty-compare register */
  SetPV((byte)0x0D);                   /* Set prescaler register according to the selected high speed CPU mode */
  /* TMRB_0_CTRL: CM=1,PCS=8,SCS=0,ONCE=0,LENGTH=0,DIR=0,COINIT=0,OUTMODE=6 */
  setRegBits(TMRB_0_CTRL,0x3006);      /* Run counter */
}

/* END SERVO2. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
